stages:
- stage: Build
  jobs:
  - job: 'Linux'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: PowerShell@2
      inputs:
          targetType: 'inline'
          script: |
            Install-Module -Name InvokeBuild -Force -Verbose -AllowClobber
          pwsh: true
      displayName: 'Install InvokeBuild'

    - task: PowerShell@2
      inputs:
          targetType: 'inline'
          script: |
            Invoke-Build -File './build.ps1' -Verbose
          pwsh: true
      displayName: 'Build Module'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.Repository.LocalPath)/Release'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Release Folder to Staging Directory'

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      displayName: 'Publish Artifact to Azure DevOps'